Repository SOMA-TIL/TIL-Frontend, pull requests merged in 2024-07, with the labels that each got.

#6 [TIL-75] 절대경로 설정
  craco.config.js
  package.json
  src/App.tsx
  src/components/pages/JoinPage/JoinPage.tsx
  src/components/pages/LoginPage/LoginPage.tsx
  src/services/api/userService.ts
  src/type/api.d.ts
  src/type/auth.d.ts
  tsconfig.json
  tsconfig.paths.json
  yarn.lock
Labels: ⚙️ setting

#7 [TIL-81] yarn 패키지 캐시 정리 및 재설치 스크립트 추가
  package.json
Labels: ⚙️ setting

#10 [TIL-82] CD worlflow error 해결
  .github/workflows/cd-dev.yml
Labels: 🐞bug

#11 [TIL-88] 변경된 로그인 API에 맞춰 응답받은 데이터 저장
  src/components/pages/LoginPage/LoginPage.tsx
  src/store/useUserInfoStore.ts
  src/type/user.d.ts
Labels: 🛠 refactor

#12 [TIL-94] 환경에 따라 zustand devtools 적용
  src/store/support.ts
  src/store/useAuthStore.ts
  src/store/useUserInfoStore.ts
Labels: 🛠 refactor

#13 [TIL-72] 기본 컴포넌트 레이아웃 작성
  .eslintignore
  .prettierignore
  public/TIL_logo.png
  public/index.html
  src/App.tsx
  src/components/layout/Footer/Footer.css
  src/components/layout/Footer/Footer.tsx
  src/components/layout/Header/Header.css
  src/components/layout/Header/Header.tsx
  src/components/layout/HeaderMenuButton/HeaderMenuButton.css
  src/components/layout/HeaderMenuButton/HeaderMenuButton.tsx
  src/components/layout/PageLayout.css
  src/components/layout/PageLayout.tsx
  src/index.tsx
Labels: ✨ feature

#14 [TIL-93] API 요청시 JWT 토큰을 자동으로 포함시켜 요청
  src/services/api/axios.ts
  src/services/cookie.ts
Labels: ✨ feature

#15 [TIL-98] 권한별(사용자의 로그인 상태) 페이지 접근 세팅
  .eslintrc.js
  src/App.tsx
  src/route.tsx
Labels: ✨ feature

#17 [TIL-102] Header 권한별로 다르게 보이도록 구성
  src/components/layout/Header/Header.tsx
  src/components/layout/HeaderMenuButton/HeaderMenuButton.tsx
  src/components/pages/LoginPage/LoginPage.tsx
  src/route.tsx
  src/store/useAuthStore.ts
Labels: 🛠 refactor

#18 [TIL-113] 로그아웃 처리 로직 구현
  src/components/layout/Header/Header.tsx
  src/services/api/userService.ts
  src/store/clear.ts
  src/store/useAuthStore.ts
  src/store/useUserInfoStore.ts
Labels: ✨ feature

#20 [TIL-105] 모의 면접 구성 화면 추가
  src/App.tsx
  src/components/layout/SelectBox/SelectBox.tsx
  src/components/layout/TabButton/TabButton.css
  src/components/layout/TabButton/TabButton.tsx
  src/components/pages/InterviewIntroPage/InterviewHistory.tsx
  src/components/pages/InterviewIntroPage/InterviewIntroPage.css
  src/components/pages/InterviewIntroPage/InterviewIntroPage.tsx
  src/components/pages/InterviewIntroPage/InterviewOrganization.tsx
Labels: ✨ feature

#21 [TIL-118] Private Route 인가 로직 on/off 기능 구현
  .env.template
  src/App.tsx
  src/route.tsx
Labels: ✨ feature

#24 [TIL-107] 백엔드 서버에서 데이터 받아서 기술 카테고리 동적 SelectBox 구성
  src/components/layout/SelectBox/SelectBox.tsx
  src/components/pages/InterviewIntroPage/InterviewIntroPage.css
  src/components/pages/InterviewIntroPage/InterviewIntroPage.tsx
  src/components/pages/InterviewIntroPage/InterviewOrganization.tsx
  src/services/api/categoryService.ts
  src/type/category.d.ts
  tsconfig.json
Labels: ✨ feature
