Repository SOMA-TIL/TIL-Frontend, pull requests merged in 2024-08, with the labels that each got.

#26 [TIL-134] 로그인 화면 스타일링 적용
  public/images/ad.png
  src/components/layout/Header/Header.style.tsx
  src/components/layout/Main/Main.style.tsx
  src/components/pages/LoginPage/LoginPage.tsx
  src/styles/ButtonStyle.tsx
  src/styles/DivStyle.tsx
  src/styles/FormStyle.tsx
  src/styles/GlobalStyle.tsx
  src/styles/InputStyle.tsx
  src/styles/length.ts
  src/styles/pallete.ts
Labels: 🎀 style

#27 [FEAT/TIL-138] 모의 면접 구성 화면 에러 처리 추가
  src/components/pages/InterviewIntroPage/InterviewOrganization.tsx
Labels: 🛠 refactor

#28 [TIL-130] header 스타일링 적용
  public/images/logout_icon.png
  src/components/layout/Header/Header.style.tsx
  src/components/layout/Header/Header.tsx
  src/components/layout/Header/HeaderMenuItem.tsx
Labels: 🎀 style

#30 [TIL-141] 로그아웃 완료시 홈 화면으로 이동
  src/components/layout/Header/Header.tsx
Labels: 🐞bug

#34 [TIL-154] 페이지 컴포넌트에서 페이지 레이아웃 설정하도록 변경
  src/App.tsx
  src/components/layout/BasicPageLayout.tsx
  src/components/pages/InterviewIntroPage/InterviewIntroPage.tsx
  src/components/pages/JoinPage/JoinPage.tsx
  src/components/pages/LoginPage/LoginPage.tsx
  src/components/pages/MainPage/MainPage.style.tsx
  src/components/pages/MainPage/MainPage.tsx
  src/components/pages/ProblemDetailPage/ProblemDetailPage.tsx
  src/components/pages/ProblemListPage/ProblemListPage.tsx
Labels: 🛠 refactor, ⚙️ setting

#35 [TIL-139] 기본 폰트(Pretendard) 설정
  src/styles/GlobalStyle.tsx
Labels: ⚙️ setting

#37 [TIL-147] CD workflow 수정
  .github/workflows/cd-dev.yml
Labels: ⚙️ setting

#39 [TIL-163] 이미지 경로 절대경로로 수정
  src/components/layout/Header/Header.tsx
  src/components/layout/Header/HeaderMenuItem.tsx
  src/components/pages/MainPage/MainPage.tsx
Labels: 🐞bug

#36 [TIL-158] DB 설계 변경에 맞게 모의 면접 구성화면 리팩토링
  src/components/pages/InterviewIntroPage/InterviewOrganization.tsx
  src/type/category.d.ts
Labels: 🛠 refactor

#41 [TIL-127] 모의 면접 생성 로직 POST API 코드 작성
  src/components/pages/InterviewIntroPage/InterviewOrganization.tsx
  src/services/api/InterviewService.ts
  src/type/interview.d.ts
Labels: ✨ feature

#44 [TIL-177] access 토큰 정보가 있을 때만 Authorization 헤더 추가
  src/services/api/axios.ts
Labels: 🐞bug

#46 [TIL-178] CD workflow에 dev env 추가
  .github/workflows/cd-dev.yml
Labels: ⚙️ setting

#48 [TIL-185] 면접 구성 화면 스타일링 적용
  src/components/layout/SelectBox/SelectBox.tsx
  src/components/layout/TabButton/TabButton.style.tsx
  src/components/layout/TabButton/TabButton.tsx
  src/components/pages/InterviewIntroPage/InterviewHistory.tsx
  src/components/pages/InterviewIntroPage/InterviewIntroPage.css
  src/components/pages/InterviewIntroPage/InterviewIntroPage.style.tsx
  src/components/pages/InterviewIntroPage/InterviewIntroPage.tsx
  src/components/pages/InterviewIntroPage/InterviewOrganization.tsx
  src/components/pages/InterviewIntroPage/OrganizationFooter.style.tsx
  src/components/pages/InterviewIntroPage/OrganizationFooter.tsx
  src/components/pages/InterviewIntroPage/SelectBar.style.tsx
  src/components/pages/InterviewIntroPage/SelectBar.tsx
  src/components/pages/InterviewIntroPage/SubHeader.style.tsx
  src/components/pages/InterviewIntroPage/SubHeader.tsx
  src/styles/pallete.ts
Labels: 🎀 style

#51 [TIL-196] 로그인 처리 결과 관련 alert창 제거
  src/components/pages/LoginPage/LoginPage.tsx
Labels: 🛠 refactor

#49 [TIL-193] 문제 리스트/상세 API 변경에 따른 리팩토링 적용
  src/components/pages/ProblemDetailPage/ProblemDetailPage.tsx
  src/components/pages/ProblemListPage/ProblemListPage.tsx
  src/services/api/problemService.ts
  src/type/problem.d.ts
Labels: 🛠 refactor

#52 [TIL-195] 기술학습 문제 제출 히스토리 API 연동
  src/components/pages/ProblemDetailPage/ProblemDetailPage.tsx
  src/components/pages/ProblemDetailPage/ProblemHistoryTab.tsx
  src/services/api/problemService.ts
  src/type/problem.d.ts
  src/utils/time.ts
Labels: ✨ feature

#53 [TIL-142] 면접 진행 화면 UX/UI, 스타일링 작업
  public/images/interviewee.png
  public/images/interviewer.png
  src/App.tsx
  src/components/layout/MinimalMain/MinimalMain.style.tsx
  src/components/layout/MinimalMain/MinimalMain.tsx
  src/components/layout/MinimalPageLayout.tsx
  src/components/pages/InterviewIntroPage/OrganizationFooter.tsx
  src/components/pages/InterviewPage/InterviewFooter.style.tsx
  src/components/pages/InterviewPage/InterviewFooter.tsx
  src/components/pages/InterviewPage/InterviewHeader.style.tsx
  src/components/pages/InterviewPage/InterviewHeader.tsx
  src/components/pages/InterviewPage/InterviewInfo.style.tsx
  src/components/pages/InterviewPage/InterviewInfo.tsx
  src/components/pages/InterviewPage/InterviewMain.style.tsx
  src/components/pages/InterviewPage/InterviewMain.tsx
  src/components/pages/InterviewPage/InterviewMessageBox.style.tsx
  src/components/pages/InterviewPage/InterviewMessageBox.tsx
  src/components/pages/InterviewPage/InterviewPage.tsx
  src/services/api/InterviewService.ts
  src/styles/pallete.ts
Labels: ✨ feature, 🎀 style

#55 [TIL-200] 카테고리 store categoryList undefined일 때 처리 로직 추가
  src/components/pages/ProblemDetailPage/ProblemDetailPage.tsx
  src/store/useCategoryStore.ts
Labels: 🐞bug

#54 [TIL-197] 로딩 store&컴포넌트 생성 및 적용
  src/components/common/loading/Loading.style.tsx
  src/components/common/loading/Loading.tsx
  src/components/pages/ProblemDetailPage/ProblemDetailPage.tsx
  src/components/pages/ProblemListPage/ProblemListPage.tsx
  src/store/useLoadingStore.ts
Labels: ✨ feature

#56 [TIL-191] 검색 바 기능 구현 & 스타일링
  package.json
  src/components/common/ant/AntStyleProvider.tsx
  src/components/pages/ProblemListPage/ProblemListPage.style.tsx
  src/components/pages/ProblemListPage/ProblemListPage.tsx
  src/components/pages/ProblemListPage/SearchBar.style.tsx
  src/components/pages/ProblemListPage/SearchBar.tsx
  src/services/api/problemService.ts
  yarn.lock
Labels: ✨ feature, 🎀 style

#57 [TIL-205] 기술학습 문제 답변 제출 후 API 응답 처리
  src/components/pages/ProblemDetailPage/ProblemDetailPage.tsx
  src/constants/grading.ts
  src/services/api/problemService.ts
  src/type/grading.d.ts
Labels: 🛠 refactor

#59 [TIL-211] 기술 학습 상세 화면 스타일링
  src/components/pages/ProblemDetailPage/ProblemDetailPage.style.tsx
  src/components/pages/ProblemDetailPage/ProblemDetailPage.tsx
  src/components/pages/ProblemDetailPage/ProblemHistoryTab.style.tsx
Labels: 🎀 style

#58 [TIL-210] 문제 리스트 전체 스타일링
  src/components/pages/ProblemListPage/ProblemListPage.style.tsx
  src/components/pages/ProblemListPage/ProblemListPage.tsx
Labels: 🎀 style

#60 [TIL-215] public image 압축
  public/images/TIL_logo.png
  public/images/ad.png
  public/images/banner.jpg
  public/images/banner.png
  public/images/interviewee.png
  public/images/interviewer.png
  public/images/logout_icon.png
  src/components/pages/MainPage/MainPage.tsx
Labels: 🛠 refactor

#61 [TIL-216] 기술학습 사용자 답변 제출 관련 리팩토링(modal, 중복 제출)
  src/components/pages/ProblemDetailPage/ProblemDetailPage.tsx
Labels: 🛠 refactor

#64 [TIL-224] 초기 사이트 로딩시 토큰 정보 설정
  src/App.tsx
  src/components/pages/LoginPage/LoginPage.tsx
  src/index.tsx
  src/services/api/authService.ts
  src/services/api/axios.ts
  src/store/clear.ts
  src/store/useAuthStore.ts
  src/type/api.d.ts
Labels: 🛠 refactor

#65 [TIL-226] 로고 이미지 수정 및 파비콘 적용
  public/images/TIL_logo.png
  public/images/favicon.ico
  public/index.html
  src/components/layout/Header/Header.style.tsx
Labels: ⚙️ setting

#67 [TIL-198] 모의 기술 진행 화면 서버 정보 연결
  src/components/pages/InterviewIntroPage/InterviewIntroPage.style.tsx
  src/components/pages/InterviewIntroPage/InterviewOrganization.tsx
  src/components/pages/InterviewIntroPage/OrganizationFooter.style.tsx
  src/components/pages/InterviewIntroPage/OrganizationFooter.tsx
  src/components/pages/InterviewPage/InterviewFooter.tsx
  src/components/pages/InterviewPage/InterviewInfo.tsx
  src/components/pages/InterviewPage/InterviewMain.tsx
  src/components/pages/InterviewPage/InterviewPage.tsx
  src/constants/interview.ts
  src/services/api/InterviewService.ts
  src/type/interview.d.ts
Labels: ✨ feature

#68 [TIL-229] 모의면접 진행 기능 프론트엔드 연결
  src/components/pages/InterviewPage/InterviewHeader.tsx
  src/components/pages/InterviewPage/InterviewMain.tsx
  src/components/pages/InterviewPage/InterviewPage.tsx
  src/services/api/InterviewService.ts
Labels: ✨ feature

#69 [TIL-230] 새로고침시 토큰 정보 재발급 기다리기
  src/App.tsx
Labels: 🐞bug

#70 feat: 모의면접 채점 결과 화면 구현
  src/App.tsx
  src/components/pages/InterviewPage/InterviewPage.tsx
  src/components/pages/InterviewPage/InterviewResultPage.style.tsx
  src/components/pages/InterviewPage/InterviewResultPage.tsx
  src/constants/interview.ts
  src/services/api/InterviewService.ts
  src/type/grading.d.ts
Labels: ✨ feature

#72 [TIL-246] 토큰 정보 재발급 로직 개선 및 로그아웃 예외처리 추가
  src/App.tsx
  src/components/layout/Header/Header.tsx
  src/services/api/authService.ts
Labels: 🛠 refactor

#73 [TIL-247] 로딩 스피너 gif로 변경
  public/images/loading.gif
  src/components/common/loading/Loading.style.tsx
  src/components/common/loading/Loading.tsx
Labels: 🛠 refactor

#76 [TIL-254] README.md 파일 기술 스택 수정
  README.md
  TIL-CLIENT/vite.env.d.ts
Labels: 📃 docs
